name: Tests

on:
  workflow_call:
    inputs:
      all_tests:
        required: true
        type: boolean
      debug_ssh_session:
        required: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  cargo-test-debug:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-2022
        exclude:
          # Avoid Mac here for now, because the CI is costly (10x of linux)
          - os: ${{ !inputs.all_tests && 'macos-latest' }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_ssh_session }}
        with:
          limit-access-to-actor: true
      - name: "Run tests"
        run: |
          ./scripts/ci-test.sh

  cargo-test-linux-release:
    if: ${{ inputs.all_tests }}
    name: "cargo test (linux, release)"
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
      - name: "Run tests"
        run: |
            rustup show -v
            cargo test --release --locked
